services:
  redis:
    image: redis:latest
    container_name: llm_project_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: llm_project_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"